describe('Sign In spec', () => {
    it('Sign In With valid details', () => {
        cy.wait(3000)
        cy.visit(Cypress.env('url'))
        cy.wait(3000)
        cy.get('.panel > .header > :nth-child(2) > a').contains('Sign In').click()
        cy.get('#email').type(Cypress.env('email'))
        cy.wait(1000)
        cy.get('#pass').type(Cypress.env('Password'))
        cy.wait(1000)
        cy.get('.login-container > .block-customer-login > .block-content > #login-form > .fieldset > .actions-toolbar > div.primary > #send2').contains("Sign In").should('be.visible').click();
        cy.wait(2000)
        cy.get(':nth-child(2) > .greet > .logged-in').should('have.text', 'Welcome, magento Software!');
        cy.wait(1000)
        cy.get('a').find('img').should('have.attr','src','https://magento.softwaretestingboard.com/pub/static/version1666447838/frontend/Magento/luma/en_US/images/logo.svg')
        cy.wait(1000)
        //Womens Selection//
        cy.get('#ui-id-4 > :nth-child(2)').contains('Women').trigger('mouseover')
        cy.wait(1000)
        cy.get('#ui-id-9').contains('Tops').trigger('mouseover')
        cy.wait(1000)
        cy.get('#ui-id-13 > span').contains('Tees').click({force : true})
        cy.wait(1000)
        cy.get('[alt="Desiree Fitness Tee"]').click({force : true})
        cy.wait(1000)
        cy.get('#option-label-size-143-item-167').click({force : true})
        cy.wait(1000)
        cy.get('#option-label-color-93-item-49').click({force : true})
        cy.wait(1000)
        cy.get('#product-addtocart-button').contains('Add to Cart').click({force : true})
        cy.wait(4000)
        // Mens Selection//
        cy.get('.logo > img').click({force : true})
        cy.wait(4000)
        cy.get('#ui-id-5 > :nth-child(2)').contains('Men').trigger('mouseover')
        cy.wait(1000)
        cy.get('#ui-id-17').contains('Tops').trigger('mouseover')
        cy.wait(1000)
        cy.get('#ui-id-20 > span').contains('Hoodies & Sweatshirts').click({force : true})
        cy.wait(1000)
        cy.get('[alt="Teton Pullover Hoodie"]').click({force : true})
        cy.wait(1000)
        cy.get('#option-label-size-143-item-167').click({force : true})
        cy.wait(1000)
        cy.get('#option-label-color-93-item-49').click({force : true})
        cy.wait(1000)
        cy.get('#product-addtocart-button').contains('Add to Cart').click({force : true})
        cy.wait(4000)
        // Gear Category//
        cy.get('.logo > img').click({force : true})
        cy.wait(4000)
        cy.get('#ui-id-6 > :nth-child(2)').contains('Gear').trigger('mouseover')
        cy.wait(1000)
        cy.get('#ui-id-25').contains('Bags').click({force : true})
        cy.wait(1000)
        cy.get('[alt="Savvy Shoulder Tote"]').click({force : true})
        cy.wait(1000)
        cy.get('#product-addtocart-button').contains('Add to Cart').click({force : true})
        cy.wait(4000)
        cy.get('.logo > img').click({force : true})
        cy.wait(4000)
        cy.get('.showcart').contains('My Cart').click({force : true})
        cy.wait(1000)
        cy.get('a.action.viewcart').contains('View and Edit Cart').click({force : true})
        cy.wait(3000)
        cy.get(':nth-child(4) > .item-actions > td > .actions-toolbar > .action-delete').click({force : true})
        cy.wait(2000)
        cy.get('button.action.primary.checkout').contains('Proceed to Checkout').click({force : true})
        cy.wait(5000)
        cy.get('.shipping-address-item').click({force : true})
        cy.get(':nth-child(1) > :nth-child(1) > .radio').click({force : true})
        cy.wait(1000)
        cy.get('.button').contains('Next').click({force : true})
        cy.wait(2000)
        cy.get('.payment-method-content > :nth-child(4) > div.primary > .action').contains('Place Order').click({force : true})
        cy.wait(2000)
        cy.get('.base').should('have.text','Thank you for your purchase!')
        cy.wait(2000)
        cy.get('.checkout-success > .actions-toolbar > div.primary > .action').click({force : true})
        cy.wait(2000)
    })
})